In [1]:
import re
import os
import nltk
import glob
import email
import string
import pandas as pd
from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from dateparser.search import search_dates

import warnings
warnings.filterwarnings('ignore')

In [2]:
for file in os.listdir(r'.\Phishing Dataset\normal'):
    file_loc = os.path.join(r'.\Phishing Dataset\normal', file)
    base = os.path.splitext(file_loc)[0]
    os.rename(file_loc, base + ".eml")

In [3]:
files = glob.glob(r'.\Phishing Dataset\normal\*.eml')
print('Total number of files:', len(files))

Total number of files: 2551

In [4]:
normal_body = []
html_tag = []
img_tag = []

for file in files:
    
    with open(file, errors="ignore") as f:
        obj = email.message_from_string(f.read())
    
    if obj.is_multipart():
        for payload in obj.get_payload():
            mail_body = payload.get_payload()
    else:
        mail_body = obj.get_payload()
    
    try:
        soup = BeautifulSoup(mail_body, 'html.parser')
        body = re.sub('\s+', ' ', soup.get_text()).strip()
        normal_body.append(body)
        html_tag.append(len(soup.findAll()))
        img_tag.append(len(soup.find_all('img')))

    except: 
        pass

In [5]:
url_count = []
dot_count = []

account = []
ebay = []
paypal = []
email = []
please = []
information = []
message = []
bank = []
policy = []
access = []
member = []
update = []


for body in normal_body:
    
    if 'account' in body.lower():
        account.append(1)
    else:
        account.append(0)
        
    if 'ebay' in body.lower():
        ebay.append(1)
    else:
        ebay.append(0)
        
    if 'paypal' in body.lower():
        paypal.append(1)
    else:
        paypal.append(0)
    
    if 'email' in body.lower():
        email.append(1)
    else:
        email.append(0)
    
    if 'please' in body.lower():
        please.append(1)
    else:
        please.append(0)
    
    if 'information' in body.lower():
        information.append(1)
    else:
        information.append(0)
    
    if 'message' in body.lower():
        message.append(1)
    else:
        message.append(0)
    
    if 'bank' in body.lower():
        bank.append(1)
    else:
        bank.append(0)
    
    if 'policy' in body.lower():
        policy.append(1)
    else:
        policy.append(0)
    
    if 'access' in body.lower():
        access.append(1)
    else:
        access.append(0)
     
    if 'member' in body.lower():
        member.append(1)
    else:
        member.append(0)
    
    if 'update' in body.lower():
        update.append(1)
    else:
        update.append(0)
        
    pattern = r"\b((?:https?://)?(?:(?:www\.)?(?:[\da-z\.-]+)\.(?:[a-z]{2,6})|(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|(?:(?:[0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,7}:|(?:[0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,5}(?::[0-9a-fA-F]{1,4}){1,2}|(?:[0-9a-fA-F]{1,4}:){1,4}(?::[0-9a-fA-F]{1,4}){1,3}|(?:[0-9a-fA-F]{1,4}:){1,3}(?::[0-9a-fA-F]{1,4}){1,4}|(?:[0-9a-fA-F]{1,4}:){1,2}(?::[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:(?:(?::[0-9a-fA-F]{1,4}){1,6})|:(?:(?::[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(?::[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(?:ffff(?::0{1,4}){0,1}:){0,1}(?:(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])|(?:[0-9a-fA-F]{1,4}:){1,4}:(?:(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])))(?::[0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])?(?:/[\w\.-]*)*/?)\b"
    url_matches = re.findall(pattern, body)
    url_count.append(len(url_matches))
    
    max_dot_count = 0
    for url in url_matches:
        dots = url.count('.')
        if max_dot_count < dots:
            max_dot_count = dots
    dot_count.append(max_dot_count)

In [9]:
df_normal = pd.DataFrame()

df_normal['HTML_tag'] = html_tag
df_normal['img_tag'] = img_tag
df_normal['dots'] = dot_count
df_normal['urls'] = url_count

df_normal['account'] = account
df_normal['ebay'] = ebay
df_normal['paypal'] = paypal
df_normal['email'] = email
df_normal['please'] = please
df_normal['information'] = information
df_normal['message'] = message
df_normal['bank'] = bank
df_normal['policy'] = policy
df_normal['access'] = access
df_normal['member'] = member
df_normal['update'] = update

df_normal['target'] = 'Normal'

df_normal

,HTML_tag,img_tag,dots,urls,account,ebay,paypal,email,please,information,message,bank,policy,access,member,update,target
0,1,0,2,4,0,0,0,0,0,0,1,0,0,0,0,0,Normal
1,0,0,3,3,0,0,0,1,0,0,0,0,0,0,0,0,Normal
2,0,0,3,3,0,0,0,1,0,0,0,0,0,0,0,0,Normal
3,0,0,2,4,0,0,0,0,0,0,1,0,0,0,0,0,Normal
4,0,0,3,4,0,0,0,1,0,0,1,0,0,0,0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,Normal
2545,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,Normal
2546,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,Normal
2547,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,Normal
2548,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,Normal

In [10]:
df_normal.to_csv(r'.\normal_data.csv', index=False)